### ISSUE TITLE
Test speedup on bigger dataset and fix

### ISSUE THREAD

**Issue by dsmits** [CARRIER-project/verticox#191]
I tried running the benchmark on the seer dataset with 10000 records but there was an unspecified error after the algorithm had converged. Figure out what happened.

It had already computed the betas:

```python
betas = {'Age': 0.01576456055045128, 'Tumor Size': 0.008796047419309616,
  'Regional Node Examined': -0.029787341132760048,
  'Reginol Node Positive': 0.0898713767528534, 'Race _Black': 0.6312762498855591,
  'Marital Status_Divorced': 0.1477687805891037}
```

**Comment by dsmits** [comment]
Running the code locally with these parameters:

```csv
parties,iterations,records,features,category
3,1,10000,6,records
````

I get this error. Maybe I'm not dividing the data in the right way:


```python
benchmark-aggregator-1        | Traceback (most recent call last):
benchmark-aggregator-1        |   File "/app/tests/test_mock.py", line 409, in <module>
benchmark-aggregator-1        |     clize.run(subcommands)
benchmark-aggregator-1        |   File "/usr/local/lib/python3.10/dist-packages/sigtools/modifiers.py", line 161, in __call__
benchmark-aggregator-1        |     return self.func(*args, **kwargs)
benchmark-aggregator-1        |   File "/usr/local/lib/python3.10/dist-packages/clize/runner.py", line 404, in run
benchmark-aggregator-1        |     ret = cli(*args)
benchmark-aggregator-1        |   File "/usr/local/lib/python3.10/dist-packages/clize/runner.py", line 271, in __call__
benchmark-aggregator-1        |     return func(*posargs, **kwargs)
benchmark-aggregator-1        |   File "/usr/local/lib/python3.10/dist-packages/clize/runner.py", line 313, in _cli
benchmark-aggregator-1        |     return func('{0} {1}'.format(name, command), *args)
benchmark-aggregator-1        |   File "/usr/local/lib/python3.10/dist-packages/clize/runner.py", line 271, in __call__
benchmark-aggregator-1        |     return func(*posargs, **kwargs)
benchmark-aggregator-1        |   File "/app/tests/test_mock.py", line 133, in run
benchmark-aggregator-1        |     results = self.run_integration_test(all_data_features, all_data_outcome, node_manager,
benchmark-aggregator-1        |   File "/app/tests/test_mock.py", line 218, in run_integration_test
benchmark-aggregator-1        |     c_index = node_manager.test()
benchmark-aggregator-1        |   File "/app/verticox/node_manager.py", line 248, in test
benchmark-aggregator-1        |     c_index = self.compute_c_index(subset=Subset.TEST)
benchmark-aggregator-1        |   File "/app/verticox/node_manager.py", line 267, in compute_c_index
benchmark-aggregator-1        |     c_index, _, _, _, _ = concordance_index_censored(self.split.test.event_happened,
benchmark-aggregator-1        |   File "/usr/local/lib/python3.10/dist-packages/sksurv/metrics.py", line 222, in concordance_index_censored
benchmark-aggregator-1        |     event_indicator, event_time, estimate = _check_inputs(
benchmark-aggregator-1        |   File "/usr/local/lib/python3.10/dist-packages/sksurv/metrics.py", line 60, in _check_inputs
benchmark-aggregator-1        |     raise ValueError("All samples are censored")
benchmark-aggregator-1        | ValueError: All samples are censored
benchmark-aggregator-1 exited with code 1
```
